### ISSUE TITLE
Failing to stay logged in

### ISSUE THREAD

**Issue by btjanaka** [ACM-UCI/ACM-UCI-Website#43]
# Failing to stay logged in

## Description

Currently, if one refreshes or goes to another tab after logging in, they get logged out.

## Suggested fix

Implement some mechanism (perhaps with cookies?) to remain logged in upon refresh

**Comment by MetaNovitia** [comment]
Added LocalStorage!

**Comment by btjanaka** [comment]
Nice! Can't wait to see it in action.
