### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by cvraut** [ACM-UCI/ACM-UCI-Website#55]
## Motivation

Nice to have

## Proposed Change

Problem tags be an editable field in problem data editing

## Alternatives

u can hack the HTML... 

## Adoption

make sure no name collisions exist or enforce that names must be unique

**Comment by cvraut** [comment]
I mean problem tags

**Comment by cvraut** [comment]
pls meta ... help

**Comment by MetaNovitia** [comment]
:3
