### ISSUE TITLE
[FEATURE REQUEST] Option to list all problems at once

### ISSUE THREAD

**Issue by btjanaka** [ACM-UCI/ACM-UCI-Website#63]
## Motivation

When choosing problems, it is a bit cumbersome to keep clicking to the next page on the Data tab.

## Proposed Change

I think it would be nice to have an option to see all problems at once on the Data tab. I don't think this makes a speed difference, considering that the problems are loaded all at once anyway.

## Alternatives

N/A

## Adoption

How will we make sure everyone can use this feature properly?
- Put a button somewhere for viewing all at once.

**Comment by MetaNovitia** [comment]
all option in data added
