### ISSUE TITLE
Track site & problem statistics [FEATURE REQUEST]

### ISSUE THREAD

**Issue by cvraut** [ACM-UCI/ACM-UCI-Website#74]
## Motivation

We need to start collecting data on how our users use the site to help design and pick better problems.

## Proposed Change

Start collecting data on any user interaction with the site: which problems were clicked? What order? how many times the hint button was clicked? how many times ppl read the solution? where the traffic is coming from? peak hours?

Also if there was a way to upvote/downvote problems and solutions (independently) this will help in deciding which problems & solutions were appreciated by the users. If there are multiple solutions for a problem this will help the users choose who's solution was the cleanest/best and we can display that one 1st.

## Alternatives

We can have Sean take notes on how ppl use the site from the back of the room, but if there are too many ppl or he falls sick ... RIP

## Adoption

Change very little with the current UX make sure the upvote system is something that fits the theme like FB's like & dislike format (intuitive and familiar). 

Just focus on collecting the data 1st, once that gets going then open a new issue on visualizations based on that data.

**Comment by MetaNovitia** [comment]
Added functionality but it makes clicking links/solution slower the first time.
