### ISSUE TITLE
Sort Problem Set by difficulty from L --> R [FEATURE REQUEST]

### ISSUE THREAD

**Issue by cvraut** [ACM-UCI/ACM-UCI-Website#75]
## Motivation

Most of our members assume that the leftmost problem is the easiest. They get stuck going after a really hard problem & get discouraged.

## Proposed Change

When displaying the problems for the day, sort them by difficulty placing the easiest one on the left and the hardest one on the right.

## Alternatives

Changing the color scheme to green, yellow, red, dark blue ... but that might not be aesthetically pleasing.

## Adoption

Change nothing else with the UX only problem order. We can also tell them when this feature has been implemented.

**Comment by MetaNovitia** [comment]
Sorted by difficulty
