### ISSUE TITLE
Update Meeting Details for Online Website

### ISSUE THREAD

**Issue by paulbaldaray** [ACM-UCI/ACM-UCI-Website#84]
- Meetings will be held on Discord from 6-8pm
- Meeting 1 problems will be available from Tuesday 8am to Thursday 8am
- Meeting 2 problems will be available from Thursday 8am to Tuesday 8am

**Comment by ryoshida28** [comment]
Updated meeting times.
Website now has functionality to set meeting time lengths.
TODO: will streamline date system to give more flexibility.
